name: Build and Release APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Cordova
      run: |
        npm install -g cordova
        cordova --version
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Setup Cordova platforms
      run: |
        cordova platform add android@latest
        
    - name: Build APK
      run: |
        cordova build android --release
        
    - name: Sign APK (Optional - if you have keystore)
      if: false  # Set to true if you want to sign APK
      run: |
        # Example signing command (replace with your keystore details)
        # jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk alias_name
        
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-files
        path: platforms/android/app/build/outputs/apk/release/*.apk
        retention-days: 30
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: MigrantWorkerApp-v${{ github.run_number }}.apk
        asset_content_type: application/vnd.android.package-archive