name: Build APK Fixed

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.0
        
    - name: Install Cordova
      run: |
        npm install -g cordova@latest
        cordova --version
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Check Cordova project
      run: |
        echo "Checking if Cordova project is properly configured..."
        if [ ! -f "config.xml" ]; then
          echo "Error: config.xml not found!"
          exit 1
        fi
        if [ ! -f "package.json" ]; then
          echo "Error: package.json not found!"
          exit 1
        fi
        echo "Cordova project files found."
        
    - name: Setup Cordova platforms
      run: |
        echo "Adding Android platform..."
        cordova platform add android@latest --verbose
        
    - name: Build APK with detailed logging
      run: |
        echo "Setting environment variables..."
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
        export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools
        
        echo "Building APK..."
        cordova build android --release --verbose --debug
        
    - name: Check build output
      run: |
        echo "Checking for APK files..."
        find platforms/android -name "*.apk" -type f
        echo "Checking build directories..."
        ls -la platforms/android/app/build/outputs/apk/ || echo "APK outputs directory not found"
        
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: apk-files
        path: platforms/android/app/build/outputs/apk/**/*.apk
        retention-days: 30
        
    - name: Upload build outputs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-outputs-failure
        path: platforms/android/app/build/outputs/
        retention-days: 7
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false