name: Build APK Complete

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 30
        build-tools: 30.0.3
        
    - name: Install Cordova
      run: npm install -g cordova
      
    - name: Install dependencies
      run: npm install
      
    - name: Check Cordova requirements
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        cordova requirements android
        
    - name: Add Android platform
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        cordova platform add android || echo "Platform may already exist"
        
    - name: Prepare build
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        cordova prepare android
        
    - name: Build APK with detailed logging
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        echo "Starting APK build..."
        cordova build android --release --verbose 2>&1 | tee build.log
        echo "Build exit code: $?"
        
    - name: Find APK files
      run: |
        echo "Searching for APK files..."
        find platforms/android -name "*.apk" -type f -exec ls -la {} \;
        echo "Checking build outputs directory:"
        ls -la platforms/android/app/build/outputs/ || echo "No outputs directory"
        ls -la platforms/android/app/build/outputs/apk/ || echo "No APK directory"
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: app-release-apk
        path: platforms/android/app/build/outputs/apk/release/*.apk
        
    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-log
        path: build.log
        retention-days: 7
        
    - name: Upload all outputs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: all-build-outputs
        path: platforms/android/app/build/outputs/
        retention-days: 7