name: Simple Cordova Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        
        # Download and install Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        
        # Set environment variables
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        
        # Accept licenses and install required packages
        yes | sdkmanager --licenses || true
        sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools"
        
    - name: Install Cordova
      run: |
        npm install -g cordova@latest
        cordova --version
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Create Cordova project if needed
      run: |
        if [ ! -f "config.xml" ]; then
          echo "Creating new Cordova project..."
          cordova create . com.pmsm.migrantworker "农民工电子围栏管理系统"
        fi
        
    - name: Add Android platform
      run: |
        # Remove existing platform if present
        if [ -d "platforms/android" ]; then
          cordova platform rm android
        fi
        
        # Add Android platform
        cordova platform add android@latest
        
    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        
        # Build with verbose output
        cordova build android --release --verbose || {
          echo "Build failed, trying debug build..."
          cordova build android --debug --verbose
        }
        
    - name: Find APK files
      run: |
        echo "Looking for APK files..."
        find platforms/android -name "*.apk" -type f || echo "No APK files found"
        
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cordova-apk
        path: platforms/android/app/build/outputs/apk/**/*.apk
        retention-days: 30